### ISSUE TITLE
Feature: expose more granular controls for selecting the desired latest tag

### ISSUE THREAD

**Issue by mdb** [jveldboom/action-conventional-versioning#12]
@jveldboom - I like where you're headed with `action-conventional-versioning`, though I have a few thoughts to noodle on...

In current implementation, `action-conventional-versioning` determines the most recent preceding semver to be the name of the tag returned by the `GET /repos/{owner}/{repo}/tags?per_page=1` GH API endpoint. However, is it worth considering scenarios where this tag name might not be the correct semver to key off of in generating a new version/release? For example...

1. The most recently created tag name might not be a semver; it might be something like `mdb-experiment`
2. The most recently created tag name might not be an "official" version; it might be a tag that was manually created out of band of official release processes as an experiment, such as `0.0.1-unofficial-mdb-experiment`.
3. The most recently created tag name might correspond to a draft GitHub release or a prerelease GitHub release and some users might like to exclude these when determining the correct preceding semver.

To protect against these scenarios -- assuming you regard them as valid -- could it be helpful to use the `GET /repos/{owner}/{repo}/releases` endpoint (rather than the `GET /repos/{owner}/{repo}/tags` endpoint) and expose some inputs such as the following...

1. `ignore_prereleases` (default `false`). If `true`, `action-conventional-versioning` ignores prereleases when determining the most recent preceding semver.
2. `ignore_drafts` (default `false`). If `true`, `action-conventional-versioning` ignores draft releases when determining the most recent preceding semver.
3. _Maybe_ even a `match_pattern` (default `^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$` (yikes :( ) ) If set, `action-conventional-versioning` ignores releases whose tag name does not match the specified pattern...Or maybe a `ignore_pattern` input would be more attractive? Or maybe I'm mistaken altogether and this is unnecessary complexity?

Whatcha think? Ultimately, I defer to your vision and none of these are hard requirements for me...just some potential issues that occurred to me.

If it's helpful, I wrote about a similar-ish problem: https://mikeball.info/blog/querying-github-release-data-with-gh-and-jq/

**Comment by jveldboom** [comment]
Yes, 100% agree with this improvement! Thank you for taking the time to write this up along with great use-cases.

A couple of thoughts on the next steps relating to the implementation steps:
- Move to update the API call to no longer look at git tags but only at releases.
- For 1 & 2, I think those are spot on. And will work towards adding that.
- For 3, I'd like to add that as a possible follow-up because I think that has some significant changes. Such as needing to query for N number of releases and then loop through them to get the last valid semver one.

Whatcha think?

**Comment by mdb** [comment]
@jveldboom 🎉 That's validating to hear we're on the same page! And I agree it may be worth punting on 3 given it's a more significant/complex change with a less obvious path towards implementation.

**Comment by jveldboom** [comment]
Implemented in #15 🎉
